---

- name: "Create Application Root"
  file:
    path={{ application_root }}
    state=directory
    owner={{ application_user }}
    group={{ application_user_group }}
    mode=0775
  sudo: yes

- name: "Copy Dist Folder For Application"
  copy:
    src=../application/dist
    dest={{ application_root }}
    owner={{ application_user }}
    group={{ application_user_group }}
    mode=0775

- name: "Install NPM"
  yum:
    name=npm
    state=latest
  sudo: yes

- name: "Execute NPM Install"
  npm:
    path={{ application_root }}/dist
    production=yes

- name: "Start POC Application"
  shell: nohup node server/server.js &
    chdir={{ application_root }}/dist
  sudo: yes
